Resources:
  # Details about the myDateTimeFunction Lambda function
  myfunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
      Runtime: java8
      MemorySize: 1024
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 300