AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A sample SAM template for deploying Lambda functions.
Resources:
  # Details about the myDateTimeFunction Lambda function
  myfunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
      Runtime: java8
      MemorySize: 1024
      Timeout: 300
    Environment:
      Variables:
        FUNCTION_NAME: reverseString
  Globals:
    Function:
      Environment:
        Variables:
          FUNCTION_NAME: reverseString