server.port: 9082
spring:
  datasource:
    url: 'jdbc:postgresql://database-1.cqx4w81mksns.eu-west-1.rds.amazonaws.com:5432/postgres'
    username: postgres
    password: tudpassword580
---
spring:
  profiles: lambda
  datasource:
    url: 'jdbc:postgresql://database-1.cqx4w81mksns.eu-west-1.rds.amazonaws.com:5432/postgres'
    username: postgres
    password: tudpassword580

  cloud:
    function:
      definition: reverseString
    stream:
      bindings:
        reverseString-out-0:
          destination: TestValidatorTopic
          content-type: application/json
      kafka:
        streams:
          binder:
            applicationId: my-function
            brokers: ${KAFKA_BROKER_HOST:b-2.testkafka.pipmpf.c4.kafka.eu-west-1.amazonaws.com:9092,b-3.testkafka.pipmpf.c4.kafka.eu-west-1.amazonaws.com:9092,b-1.testkafka.pipmpf.c4.kafka.eu-west-1.amazonaws.com:9092}
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
  kafka:
    bootstrap-servers: ${KAFKA_BROKER_HOST:b-2.testkafka.pipmpf.c4.kafka.eu-west-1.amazonaws.com:9092,b-3.testkafka.pipmpf.c4.kafka.eu-west-1.amazonaws.com:9092,b-1.testkafka.pipmpf.c4.kafka.eu-west-1.amazonaws.com:9092}