server.port: 9082

---
spring:
  profiles: lambda
  cloud:
    stream:
      bindings:
        output:
          destination: testProcessTopic
          content-type: application/json
      kafka:
        streams:
          binder:
            applicationId: my-function
            brokers: ${KAFKA_BROKER_HOST:b-1.tudcluster.4sdxvs.c2.kafka.eu-west-1.amazonaws.com:9092}
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
  kafka:
    bootstrap-servers: ${KAFKA_BROKER_HOST:b-1.tudcluster.4sdxvs.c2.kafka.eu-west-1.amazonaws.com:9092}